schema_version = "1.0.0"

id = "pataz_auto_hide_overlays"
version = "5.2.0"
name = "Pataz Auto Hide Overlays"
tagline = "Hides overlays during transform or playback"
maintainer = "Daniel Salazar"
type = "add-on"

website = "https://blenderaddon.com/"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 Daniel Salazar",]